brand:
  name: Curious Applications
menu-string: Menu



copyright: Copyright © 2019 Curious Applications.  All rights reserved

nav:
  - title: Services
    url: '/#services'
  - title: Approach
    url: '/#approach'    
  - title: Highlights
    url: '/#about'
  - title: About
    url: '/#team'
  - title: 'Contact'
    url: '/#contact'