brand:
  name: Curious Applications
menu-string: Menu

copyright: Copyright © 2023 Curious Applications.  All rights reserved

nav:
  - title: Services
    url: '/#services'
  - title: Approach
    url: '/#approach'    
  - title: Highlights
    url: '/#highlights'
  - title: About
    url: '/#team'
  - title: 'Contact'
    url: '/#contact'

social-buttons:
  - icon: fab fa-linkedin
    url: https://www.linkedin.com/in/chris-conover-ios/
  - icon: fab fa-angellist
    url: https://angel.co/chris-conover
  - icon: fab fa-stack-overflow
    url: https://stackoverflow.com/users/2171044/chris-conover
  - icon: fab fa-twitter
    url: https://twitter.com/chrislconover
